// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var TextRe      = require("bs-react-native/src/components/textRe.js");
var ReasonReact = require("reason-react/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Component");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, TextRe.Text[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["Hello world"]));
    });
  return newrecord;
}

var component$1 = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.make      = make;
exports.component = component$1;
/* component Not a pure module */
